### PR TITLE
Added typescript definition file

### PR DESCRIPTION
**Pull request by u12206050**
With this file in the project it is able to import events into a TS project like so:
import { EventEmitter } from 'events/events';
Events is thus much more supportive and useable in type strict projects

### CODE REVIEW

**Comment by AbraaoAlves** [comment]
You can add info on package.json like this: 
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by goto-bus-stop** [comment]
Do we need this here when `events` is also included in `@types/node`?

**Comment by fhelwanger** [comment]
I think this can be closed because this already exists: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/events

**Comment by goto-bus-stop** [comment]
Thanks for the link @fhelwanger!

Yes, i think it'll be best for people to use either the `@types/node` or the `@types/events` package for this.

Thanks @u12206050 for the PR!

**Pull request closed without merging**
