### PR TITLE
Update

### PR DESCRIPTION
**Pull request by OguzhanUmutlu**
it should be like that i suppose

### CODE REVIEW

**Comment by lyertia** [comment]
i think its better and its working

**Comment by OguzhanUmutlu** [comment]
> i think its better and its working

yes!

**Comment by goto-bus-stop** [comment]
Thanks for the PR! The purpose of this package is to provide a full-featured implementation of the builtin node.js `events` module API that works on as many platforms as possible. So any changes need to match this: https://nodejs.org/api/events.html and work on old browsers that do not have class syntax.

The implementation in this PR is maybe better suited for a separate package that you could release yourself :)

**Comment by OguzhanUmutlu** [comment]
uh makes sense sorry

**Pull request closed without merging**
