### PR TITLE
clean code EventEmitter

### PR DESCRIPTION
**Pull request by uxitten**
split all method

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
Thanks for the PR! This module copies the Node core EventEmitter code though; it's easier to do that when it's in a single file, [like it is in Node](https://github.com/nodejs/node/blob/8476815f01bb4e60693f1fc8a06f384c903396da/lib/events.js).

**Comment by uxitten** [comment]
I did it to keep the code up and so it's easier

**Comment by goto-bus-stop** [comment]
I think it's easier to apply updates if it's more similar to Node, because we can copy paste into the file and don't have to think about converting it to the modular structure.

**Comment by uxitten** [comment]
@goto-bus-stop thank's

**Pull request closed without merging**
